name: Build and Deploy to Server

on:
  push:
    branches:
      - github-actions

jobs:
  deploy:
    env:
      BASE_PATH: /~honai/demo/covid-19
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Build Project
        env:
          API_URL: ${{ secrets.API_URL }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        run: |
          mkdir -p src/pages$BASE_PATH
          mv src/pages/[!_]*.jsx src/pages$BASE_PATH
          npm install
          npm run build
          npm run export
          mv out/_next out$BASE_PATH
          mv out/images out$BASE_PATH
      - name: Deploy to Server
        env:
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
          SSH_PUBLIC: ${{ secrets.SSH_PUBLIC }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_USER: ${{ secrets.SSH_USER }}
          REMOTE_1: ${{ secrets.REMOTE_1 }}
          REMOTE_2: ${{ secrets.REMOTE_2 }}
        run: |
          echo $SSH_PRIVATE > id_rsa
          chmod 600 id_rsa
          echo $KNOWN_HOSTS >> ~/.ssh/known_hosts
          rsync -av --delete --dry-run -e "ssh -i id_rsa -o ProxyCommand=\"ssh -W %h:%p $REMOTE_1\" $REMOTE_2" out$BASE_PATH/ $SSH_USER:$DEPLOY_PATH
